name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate Unity YAML
      uses: webbertakken/unity-test-runner@v2.0
      with:
        unityVersion: 2021.3.0f1
        testMode: editmode
    - name: Lint C#
      uses: github/super-linter@v5
      env:
        VALIDATE_CSHARP: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
